---
slackChannel: "eco-build"
initialReleaseTag: '3.5.1.0-eep' # Use only for release build
whitesourceScan: true
build:
  - name: ubuntu
    imageCustom: devops/buildimages/ubuntu/image.sh
    basicBuildCommands: "_BUILD_ENV_VARS_ devops/scripts/build.sh"
    hostmachine_jenkins_label: "ubuntu16"
  - name: centos
    imageCustom: devops/buildimages/centos/image.sh
    basicBuildCommands: "_BUILD_ENV_VARS_ devops/scripts/build.sh"
    hostmachine_jenkins_label: "redhat8"
    rpmSign: true

# "_DOCKER_REGISTRY_" and "_BUILD_ENV_VARS_" names will be generated and added automatically during the build
