#!/bin/sh

set -e
    
case "$1" in
    upgrade)
        echo "postrm called with argument \`$1'" >&2
    ;;

    remove|purge|disappear)
        echo "postrm called with argument \`$1'" >&2
    ;;

    abort-install|abort-upgrade|failed-upgrade)
        echo "postrm called with argument \`$1'" >&2
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
